AWSTemplateFormatVersion: "2010-09-09"

Description: "Ingestion Pipeline Bucket and Queues for incoming json"

Parameters:

  Prefix:
    Type: String
    Description: "Resource name prefix used to help ensure resource name uniqueness and promote template portability between environments"
    Default: "ingest"

  IncomingJsonBucketSuffix:
    Type: String
    Description: "Name suffix of the S3 source bucket that will be created to receive incoming json files"
    Default: "bckt-curation-json"

Resources:

  IncomingJsonBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${Prefix}-${IncomingJsonBucketSuffix}"
      NotificationConfiguration:
        QueueConfigurations:
          - Event: "s3:ObjectCreated:*"
            Queue: !GetAtt IncomingJsonToCuratedJsonQueue.Arn
            Filter: 
              S3Key:
                Rules:
                  - Name: suffix
                    Value: ".json"

  IncomingJsonToCuratedJsonQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Prefix}-queue-incoming-json-to-curated-json"
      RedrivePolicy:
        maxReceiveCount: 5
        deadLetterTargetArn:
          Fn::GetAtt:
            - IncomingJsonToCuratedJsonDeadLetterQueue
            - Arn
  
  IncomingJsonToCuratedJsonDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Prefix}-dlq-incoming-json-to-curated-json"

  IncomingJsonToCuratedJsonQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref IncomingJsonToCuratedJsonQueue
      PolicyDocument:
        Id: SQSQueuePolicy
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sqs:SendMessage
            Resource: !GetAtt IncomingJsonToCuratedJsonQueue.Arn
            Principal:
              Service: s3.amazonaws.com
            Condition:
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:s3:::${Prefix}-${IncomingJsonBucketSuffix}"

Outputs:
  IncomingJsonBucketName:
    Description: "Name of the Incoming Json Bucket"
    Value: !Ref IncomingJsonBucket

  IncomingJsonToCuratedJsonQueueArn:
    Description: "ARN of the SQS Queue between Incoming Json and Curated Json Buckets"
    Value: !GetAtt IncomingJsonToCuratedJsonQueue.Arn
