AWSTemplateFormatVersion: "2010-09-09"

Description: "This example template shows how to create an ingestion pipeline using Lambda, SQS and S3 Buckets"

Parameters:

  Prefix:
    Type: String
    Description: "Resource name prefix used to help ensure resource name uniqueness and promote template portability between environments"
    Default: "ingest"

Resources:

  # Buckets & Queues

  IncomingJsonBucketStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./nested/bucket-incoming-json.yml
      Parameters:
        Prefix: !Ref Prefix
        IncomingJsonBucketSuffix: "bckt-incoming-json"
        
  IncomingCsvBucketStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./nested/bucket-incoming-csv.yml
      Parameters:
        Prefix: !Ref Prefix
        IncomingCsvBucketSuffix: "bckt-incoming-csv"

  CuratedJsonBucketStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./nested/bucket-curated-json.yml
      Parameters:
        Prefix: !Ref Prefix
        CuratedJsonBucketSuffix: "bckt-curation-json"

  # Lamdas

  CopyIncomingJsonToCuratedJsonLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./nested/lambda/lambda-copy-incoming-json-to-curated-json.yml
      Parameters:
        Prefix: !Ref Prefix
        CopyIncomingJsonToCuratedJsonLambdaName: "ingest-lmbda-copy-incoming-json-to-curated-json"
        IncomingJsonBucketName: !GetAtt IncomingJsonBucketStack.Outputs.IncomingJsonBucketName
        IncomingJsonToCuratedJsonQueueArn: !GetAtt IncomingJsonBucketStack.Outputs.IncomingJsonToCuratedJsonQueueArn
        CuratedJsonBucketName: !GetAtt CuratedJsonBucketStack.Outputs.CuratedJsonBucketName

  CopyIncomingCsvToCuratedJsonLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./nested/lambda/lambda-copy-incoming-csv-to-curated-json.yml
      Parameters:
        Prefix: !Ref Prefix
        ConvertIncomingCsvToCuratedJsonLambdaName: "lmbda-convert-incoming-csv-to-curated-json"
        IncomingCsvBucketName: !GetAtt IncomingCsvBucketStack.Outputs.IncomingCsvBucketName
        IncomingCsvToCuratedJsonQueueArn: !GetAtt IncomingCsvBucketStack.Outputs.IncomingCsvToCuratedJsonQueueArn
        CuratedJsonBucketName: !GetAtt CuratedJsonBucketStack.Outputs.CuratedJsonBucketName
