AWSTemplateFormatVersion: "2010-09-09"

Description: "Ingestion Pipeline Lambda to copy incoming csv to curated json bucket"

Parameters:

  Prefix:
    Type: String
    Description: "Resource name prefix used to help ensure resource name uniqueness and promote template portability between environments"
    Default: "ingest"

  ConvertIncomingCsvToCuratedJsonLambdaName:
    Type: String
    Description: "Name of Lambda function for converting/uploading files from the Incoming Csv Bucket to the Curated Json Bucket"

  IncomingCsvBucketName:
    Type: String
    Description: "Name of the existing Incoming CSV Bucket"

  CuratedJsonBucketName:
    Type: String
    Description: "Name of the existing Curated Json Bucket"

  IncomingCsvToCuratedJsonQueueArn:
    Type: String
    Description: "ARN of the existing SQS Queue between Incoming Csv and Curated Json Buckets"

Resources:

  # Incoming CSV to Curated

  ConvertIncomingCsvToCuratedJsonLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${Prefix}-${ConvertIncomingCsvToCuratedJsonLambdaName}"
      Description: "Converts/uploads files from the Incoming Csv Bucket to the Curated Json Bucket"
      Runtime: python3.8
      Handler: index.lambda_handler
      Role: !GetAtt ConvertIncomingCsvToCuratedJsonLambdaExecutionRole.Arn
      Timeout: 30 # cannot be greater than queue timeout
      Environment:
        Variables:
          DESTINATION_BUCKET_NAME: !Ref CuratedJsonBucketName
      Code:
        ZipFile: |
          import os
          import json
          import boto3
          import logging
          from urllib.parse import unquote_plus
          import csv
          from io import StringIO

          logger = logging.getLogger()
          logger.setLevel('INFO')

          s3 = boto3.client('s3')

          destination_bucket_name = os.environ['DESTINATION_BUCKET_NAME']

          def convert_csv_to_json(csv_data):
              # Read CSV data from memory
              csv_stream = StringIO(csv_data)
              csv_reader = csv.DictReader(csv_stream)

              # Convert CSV data to a list of dictionaries
              data = list(csv_reader)

              # Convert data to JSON format
              json_data = json.dumps(data)

              return json_data

          def process_s3_event_record(s3_event_record):  
            source_bucket_name = s3_event_record['s3']['bucket']['name']
            source_key = unquote_plus(s3_event_record['s3']['object']['key'])

            logger.info(f"Reading CSV from '{source_bucket_name}/{source_key}'")
            response = s3.get_object(Bucket=source_bucket_name, Key=source_key)
            csv_data = response['Body'].read().decode('utf-8')

            logger.info(f"Converting CSV to JSON")
            json_data = convert_csv_to_json(csv_data)

            destination_key = f'{source_key}.json'
            logger.info(f"Uploading generated CSV to '{destination_bucket_name}/{destination_key}'")
            s3.put_object(Body = json_data, Bucket=destination_bucket_name, Key=destination_key)

          def lambda_handler(event, context):
            logger.info(f"event: {json.dumps(event)}")
            messages_to_reprocess = []
            
            for sqs_record in event['Records']:
              try:
                logger.info(f"Processing SQS Record with Message Id: {sqs_record['messageId']}")
                s3_event_records = json.loads(sqs_record['body'])['Records']
                for s3_event_record in s3_event_records:
                    process_s3_event_record(s3_event_record)
              except Exception as e:
                logger.warning(f"Failed to process SQS Record with Message Id: {sqs_record['messageId']}")
                messages_to_reprocess.append({"itemIdentifier": sqs_record['messageId']})
                logger.error(e)
            
            if len(messages_to_reprocess) > 0:
              logger.error(f"Batch Item Failures: {messages_to_reprocess}")
            
            batch_failure_response = {"batchItemFailures": messages_to_reprocess}
            return batch_failure_response

  ConvertIncomingCsvToCuratedJsonLambdaEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      EventSourceArn: !Ref IncomingCsvToCuratedJsonQueueArn
      FunctionName: !Ref ConvertIncomingCsvToCuratedJsonLambda
      FunctionResponseTypes:
        - ReportBatchItemFailures
      Enabled: True

  ConvertIncomingCsvToCuratedJsonLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Prefix}-lmbdaexec-copy-incoming-csv-to-curated-json"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecutionRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
        - PolicyName: AccessQueue
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !Ref IncomingCsvToCuratedJsonQueueArn
        - PolicyName: "ReadFromIncomingCsvBucket"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - !Sub "arn:aws:s3:::${IncomingCsvBucketName}"
                  - !Sub "arn:aws:s3:::${IncomingCsvBucketName}/*"
        - PolicyName: "WriteToCuratedJsonBucket"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource:
                  - !Sub "arn:aws:s3:::${CuratedJsonBucketName}"
                  - !Sub "arn:aws:s3:::${CuratedJsonBucketName}/*"
