AWSTemplateFormatVersion: "2010-09-09"

Description: "This example template shows how to create an ingestion pipeline using Lambda, SQS and S3 Buckets"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label: 
          default: "Curated Bucket Parameters"
        Parameters: 
          - CuratedJsonBucketName
      - Label:
          default: "Incoming Json to Curated Json Parameters"
        Parameters:
          - IncomingJsonBucketName
          - IncomingJsonToCuratedJsonQueueName
          - IncomingJsonToCuratedJsonDeadLetterQueueName
          - CopyIncomingJsonToCuratedJsonLambdaName
          - CopyIncomingJsonToCuratedJsonLambdaExecutionRoleName
      - Label:
          default: "Incoming Csv to Curated Json Parameters"
        Parameters:
          - IncomingCsvBucketName
          - IncomingCsvToCuratedJsonQueueName
          - IncomingCsvToCuratedJsonDeadLetterQueueName
          - ConvertIncomingCsvToCuratedJsonLambdaName
          - CopyIncomingCsvToCuratedJsonLambdaExecutionRoleName

Parameters:

  # Curated Bucket

  CuratedJsonBucketName:
    Type: String
    Description: "Name of the S3 destination bucket that will be created to store curated json files"
    Default: "ingest-bckt-curation-json"

  # Incoming Json to Curated Json

  IncomingJsonBucketName:
    Type: String
    Description: "Name of the S3 source bucket that will be created to receive incoming json files"
    Default: "ingest-bckt-incoming-json"

  IncomingJsonToCuratedJsonQueueName:
    Type: String
    Description: "Name of the SQS Queue between Incoming Json and Curated Json Buckets"
    Default: "ingest-queue-incoming-json-to-curated-json"

  IncomingJsonToCuratedJsonDeadLetterQueueName:
    Type: String
    Description: "Name of Dead Letter Queue for Incoming Json To Curated Json Queue"
    Default: "ingest-dlq-incoming-json-to-curated-json"

  CopyIncomingJsonToCuratedJsonLambdaName:
    Type: String
    Description: "Name of Lambda function for copying files from the Incoming Json Bucket to the Curated Json Bucket"
    Default: "ingest-lmbda-copy-incoming-json-to-curated-json"

  CopyIncomingJsonToCuratedJsonLambdaExecutionRoleName:
    Type: String
    Description: "Name of Lambda Execution Role for copying incoming Csv files from the Incoming Csv Bucket to the Curated Json Bucket"
    Default: "ingest-lmbdaexec-copy-incoming-json-to-curated-json"

  # Incoming Csv to Curated Json

  IncomingCsvBucketName:
    Type: String
    Description: "Name of the S3 source bucket that will be created to receive incoming csv files"
    Default: "ingest-bckt-incoming-csv"

  IncomingCsvToCuratedJsonQueueName:
    Type: String
    Description: s
    Default: "ingest-queue-incoming-csv-to-curated-json"

  IncomingCsvToCuratedJsonDeadLetterQueueName:
    Type: String
    Description: "Name of Dead Letter Queue for Incoming Csv To Curated Json Queue"
    Default: "ingest-dlq-incoming-csv-to-curated-csv"

  ConvertIncomingCsvToCuratedJsonLambdaName:
    Type: String
    Description: "Name of Lambda function for converting/uploading files from the Incoming Csv Bucket to the Curated Json Bucket"
    Default: "ingest-lmbda-convert-incoming-csv-to-curated-json"

  CopyIncomingCsvToCuratedJsonLambdaExecutionRoleName:
    Type: String
    Description: "Name of Lambda Execution Role for converting/uploading incoming Csv files from the Incoming Csv Bucket to the Curated Json Bucket"
    Default: "ingest-lmbdaexec-copy-incoming-csv-to-curated-json"

Resources:

  # Curated Bucket

  CuratedJsonBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref CuratedJsonBucketName

  # Incoming Json to Curated Json

  IncomingJsonBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref IncomingJsonBucketName
      NotificationConfiguration:
        QueueConfigurations:
          - Event: "s3:ObjectCreated:*"
            Queue: !GetAtt IncomingJsonToCuratedJsonQueue.Arn
            Filter: 
              S3Key:
                Rules:
                  - Name: suffix
                    Value: ".json"

  IncomingJsonToCuratedJsonQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref IncomingJsonToCuratedJsonQueueName
      RedrivePolicy:
        maxReceiveCount: 5
        deadLetterTargetArn:
          Fn::GetAtt:
            - IncomingJsonToCuratedJsonDeadLetterQueue
            - Arn
  
  IncomingJsonToCuratedJsonDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref IncomingJsonToCuratedJsonDeadLetterQueueName

  CopyIncomingJsonToCuratedJsonLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref CopyIncomingJsonToCuratedJsonLambdaName
      Description: "Copies files from the Incoming Json Bucket to the Curated Json Bucket"
      Runtime: python3.8
      Handler: index.lambda_handler
      Role: !GetAtt CopyIncomingJsonToCuratedJsonLambdaExecutionRole.Arn
      Timeout: 30 # cannot be greater than queue timeout
      Environment:
        Variables:
          DESTINATION_BUCKET_NAME: !Ref CuratedJsonBucketName
      Code:
        ZipFile: |
          import os
          import json
          import boto3
          import logging
          from urllib.parse import unquote_plus

          logger = logging.getLogger()
          logger.setLevel('INFO')

          s3 = boto3.resource('s3')

          destination_bucket_name = os.environ['DESTINATION_BUCKET_NAME']

          def process_s3_event_record(s3_event_record):
            
            source_bucket_name = s3_event_record['s3']['bucket']['name']
            key = unquote_plus(s3_event_record['s3']['object']['key'])
            
            logger.info(f"Copying '{source_bucket_name}/{key}' to '{destination_bucket_name}/{key}'")
            copy_source = {'Bucket': source_bucket_name, 'Key': key}
            destination_bucket = s3.Bucket(destination_bucket_name)
            destination_bucket.copy(copy_source, key)

          def lambda_handler(event, context):
            logger.info(f"event: {json.dumps(event)}")
            messages_to_reprocess = []
            
            for sqs_record in event['Records']:
              try:
                logger.info(f"Processing SQS Record with Message Id: {sqs_record['messageId']}")
                s3_event_records = json.loads(sqs_record['body'])['Records']
                for s3_event_record in s3_event_records:
                    process_s3_event_record(s3_event_record)
              except Exception as e:
                logger.warning(f"Failed to process SQS Record with Message Id: {sqs_record['messageId']}")
                messages_to_reprocess.append({"itemIdentifier": sqs_record['messageId']})
                logger.error(e)
            
            if len(messages_to_reprocess) > 0:
              logger.error(f"Batch Item Failures: {messages_to_reprocess}")
            
            batch_failure_response = {"batchItemFailures": messages_to_reprocess}
            return batch_failure_response

  CopyIncomingJsonToCuratedJsonLambdaEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      EventSourceArn: !GetAtt IncomingJsonToCuratedJsonQueue.Arn
      FunctionName: !Ref CopyIncomingJsonToCuratedJsonLambda
      FunctionResponseTypes:
        - ReportBatchItemFailures
      Enabled: True

  CopyIncomingJsonToCuratedJsonLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref CopyIncomingJsonToCuratedJsonLambdaExecutionRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecutionRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
        - PolicyName: AccessQueue
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt IncomingJsonToCuratedJsonQueue.Arn
        - PolicyName: "ReadFromIncomingJsonBucket"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - !Sub "arn:aws:s3:::${IncomingJsonBucketName}"
                  - !Sub "arn:aws:s3:::${IncomingJsonBucketName}/*"
        - PolicyName: "WriteToCuratedJsonBucket"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource:
                  - !Sub "arn:aws:s3:::${CuratedJsonBucketName}"
                  - !Sub "arn:aws:s3:::${CuratedJsonBucketName}/*"

  IncomingJsonToCuratedJsonQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref IncomingJsonToCuratedJsonQueue
      PolicyDocument:
        Id: SQSQueuePolicy
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sqs:SendMessage
            Resource: !GetAtt IncomingJsonToCuratedJsonQueue.Arn
            Principal:
              Service: s3.amazonaws.com
            Condition:
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:s3:::${IncomingJsonBucketName}"


  # Incoming Csv to Curated Json

  IncomingCsvBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref IncomingCsvBucketName
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt IncomingCsvToCuratedJsonQueue.Arn
            Filter: 
              S3Key:
                Rules:
                  - Name: suffix
                    Value: ".csv"

  IncomingCsvToCuratedJsonQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref IncomingCsvToCuratedJsonQueueName
      RedrivePolicy:
        maxReceiveCount: 5
        deadLetterTargetArn:
          Fn::GetAtt:
            - IncomingCsvToCuratedJsonDeadLetterQueue
            - Arn
  
  IncomingCsvToCuratedJsonDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref IncomingCsvToCuratedJsonDeadLetterQueueName

  ConvertIncomingCsvToCuratedJsonLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref ConvertIncomingCsvToCuratedJsonLambdaName
      Description: "Converts/uploads files from the Incoming Csv Bucket to the Curated Json Bucket"
      Runtime: python3.8
      Handler: index.lambda_handler
      Role: !GetAtt ConvertIncomingCsvToCuratedJsonLambdaExecutionRole.Arn
      Timeout: 30 # cannot be greater than queue timeout
      Environment:
        Variables:
          DESTINATION_BUCKET_NAME: !Ref CuratedJsonBucketName
      Code:
        ZipFile: |
          import os
          import json
          import boto3
          import logging
          from urllib.parse import unquote_plus
          import csv
          from io import StringIO

          logger = logging.getLogger()
          logger.setLevel('INFO')

          s3 = boto3.client('s3')

          destination_bucket_name = os.environ['DESTINATION_BUCKET_NAME']

          def convert_csv_to_json(csv_data):
              # Read CSV data from memory
              csv_stream = StringIO(csv_data)
              csv_reader = csv.DictReader(csv_stream)

              # Convert CSV data to a list of dictionaries
              data = list(csv_reader)

              # Convert data to JSON format
              json_data = json.dumps(data)

              return json_data

          def process_s3_event_record(s3_event_record):  
            source_bucket_name = s3_event_record['s3']['bucket']['name']
            source_key = unquote_plus(s3_event_record['s3']['object']['key'])

            logger.info(f"Reading CSV from '{source_bucket_name}/{source_key}'")
            response = s3.get_object(Bucket=source_bucket_name, Key=source_key)
            csv_data = response['Body'].read().decode('utf-8')

            logger.info(f"Converting CSV to JSON")
            json_data = convert_csv_to_json(csv_data)

            destination_key = f'{source_key}.json'
            logger.info(f"Uploading generated CSV to '{destination_bucket_name}/{destination_key}'")
            s3.put_object(Body = json_data, Bucket=destination_bucket_name, Key=destination_key)

          def lambda_handler(event, context):
            logger.info(f"event: {json.dumps(event)}")
            messages_to_reprocess = []
            
            for sqs_record in event['Records']:
              try:
                logger.info(f"Processing SQS Record with Message Id: {sqs_record['messageId']}")
                s3_event_records = json.loads(sqs_record['body'])['Records']
                for s3_event_record in s3_event_records:
                    process_s3_event_record(s3_event_record)
              except Exception as e:
                logger.warning(f"Failed to process SQS Record with Message Id: {sqs_record['messageId']}")
                messages_to_reprocess.append({"itemIdentifier": sqs_record['messageId']})
                logger.error(e)
            
            if len(messages_to_reprocess) > 0:
              logger.error(f"Batch Item Failures: {messages_to_reprocess}")
            
            batch_failure_response = {"batchItemFailures": messages_to_reprocess}
            return batch_failure_response

  ConvertIncomingCsvToCuratedJsonLambdaEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      EventSourceArn: !GetAtt IncomingCsvToCuratedJsonQueue.Arn
      FunctionName: !Ref ConvertIncomingCsvToCuratedJsonLambda
      FunctionResponseTypes:
        - ReportBatchItemFailures
      Enabled: True

  ConvertIncomingCsvToCuratedJsonLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref CopyIncomingCsvToCuratedJsonLambdaExecutionRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecutionRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
        - PolicyName: AccessQueue
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt IncomingCsvToCuratedJsonQueue.Arn
        - PolicyName: "ReadFromIncomingCsvBucket"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - !Sub "arn:aws:s3:::${IncomingCsvBucketName}"
                  - !Sub "arn:aws:s3:::${IncomingCsvBucketName}/*"
        - PolicyName: "WriteToCuratedJsonBucket"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource:
                  - !Sub "arn:aws:s3:::${CuratedJsonBucketName}"
                  - !Sub "arn:aws:s3:::${CuratedJsonBucketName}/*"

  IncomingCsvToCuratedJsonQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref IncomingCsvToCuratedJsonQueue
      PolicyDocument:
        Id: SQSQueuePolicy
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "sqs:SendMessage"
            Resource: !GetAtt IncomingCsvToCuratedJsonQueue.Arn
            Principal:
              Service: s3.amazonaws.com
            Condition:
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:s3:::${IncomingCsvBucketName}"
